version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: fuel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 384555
    ports:
      - "5433:5432" # Allows Eclipse on host to access Postgres on 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data

  fuel-backend:
    build: .
    container_name: fuel-backend
    depends_on:
      - postgres-db
    ports:
      - "7076:7075" # Docker backend exposed on host port 7076
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:7076/api
    container_name: fuel-frontend
    depends_on:
      - fuel-backend
    ports:
      - "3001:3000" # Docker React app on 3001

volumes:
  postgres-data: