--
-- PostgreSQL database dump
--

\restrict IVb4fRNlnSQVzzWeRTU5m3S7NY21Hi0jKL2HzyfJ0WkctKq1RCALWdg0vOj9LMc

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    active boolean NOT NULL,
    department character varying(255) NOT NULL,
    email character varying(255),
    employee_id character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    "position" character varying(255) NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fuel_stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fuel_stock (
    id bigint NOT NULL,
    fuel_type character varying(20),
    quantity_liters double precision
);


ALTER TABLE public.fuel_stock OWNER TO postgres;

--
-- Name: fuel_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fuel_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fuel_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fuel_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fuel_transaction (
    id bigint NOT NULL,
    driver_name character varying(255),
    fuel_type character varying(255),
    liters double precision,
    transaction_date timestamp(6) without time zone,
    vehicle_id bigint
);


ALTER TABLE public.fuel_transaction OWNER TO postgres;

--
-- Name: fuel_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fuel_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fuel_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255),
    role character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicle (
    id bigint NOT NULL,
    department character varying(255),
    model character varying(255),
    plate_number character varying(255),
    status character varying(255),
    employee_id bigint
);


ALTER TABLE public.vehicle OWNER TO postgres;

--
-- Name: vehicle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (id, active, department, email, employee_id, first_name, last_name, phone, "position") FROM stdin;
2	t	Transport	abe@example.com	EMP002	Abebe	Molla	0912345678	Driver
3	t	Transport	abe@example.com	EMP003	Abebe	Molla	0912345678	Driver
1	t	Transport	abebe@example.com	EMP001	Abebe	Bekele	0911223344	Supervisor
4	t	HR	abe@example.com	EMP005	Meaza	Taye	0912345678	HR-ooficer
5	t	Transport	kebe@example.com	EMP008	Kebede	Tamrat	0912345678	Driver
\.


--
-- Data for Name: fuel_stock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fuel_stock (id, fuel_type, quantity_liters) FROM stdin;
10	gear oil	2000
1	diesel	1900
2	petrol	2800
\.


--
-- Data for Name: fuel_transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fuel_transaction (id, driver_name, fuel_type, liters, transaction_date, vehicle_id) FROM stdin;
3	Abebe	Diesel	50	2026-06-03 21:54:54.322169	1
4	Abebe	Diesel	50	2026-06-04 00:01:13.968874	1
5	Ahmed	Diesel	60	2026-06-04 00:02:39.65151	2
6	Abebe	Diesel	90	2026-06-04 10:07:52.405562	1
7	Abebe	Diesel	100	2026-06-04 10:17:29.257552	1
8	Abebe	Diesel	50	2026-06-09 00:54:30.045208	1
9	Abebe	Diesel	600	2026-06-09 00:55:06.616496	1
11	Abebe	Diesel	550	2026-06-18 11:01:06.015121	1
12	Abebe	petrol	50	2026-06-18 12:19:05.318372	1
13	Abebe	petrol	150	2026-06-18 15:07:34.568376	1
14	Abebe	diesel	80	2026-06-20 14:18:13.456153	1
15	Abebe	diesel	5	2026-06-20 14:18:43.305629	1
16	ahmed	diesel	35	2026-06-20 15:24:42.743907	1
17	ahmed	diesel	100	2026-06-29 23:46:31.714487	1
18	ahmed	diesel	500	2026-07-01 14:58:09.958873	1
10	Abebe	gear oil	100	2026-07-22 00:34:39.448659	1
19	Abebe	diesel	15	2026-07-22 00:48:33.113813	1
1	Abebe	diesel	100	2026-07-22 14:45:14.132091	1
20	Abebe	diesel	50	2026-07-22 21:25:57.436625	1
21	Ahmed	diesel	60	2026-07-23 01:18:52.396737	2
22	Abebe	diesel	50	2026-06-03 21:54:54.322169	1
23	Abebe	diesel	50	2026-08-04 12:30:16.407267	1
24	Abebe	petrol	100	2026-08-04 12:32:45.534351	1
25	Abebe	petrol	100	2026-06-03 21:54:54.322169	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, role, username) FROM stdin;
2	$2a$10$Vo4wZBe5.vK/PvS.CPJCu.JLyZ3ErMJt8kEIl6SY6pjIGUZZq6cuS	USER	user
3	$2a$10$Vo4wZBe5.vK/PvS.CPJCu.JLyZ3ErMJt8kEIl6SY6pjIGUZZq6cuS	MANAGER	manager
4	$2a$10$Vo4wZBe5.vK/PvS.CPJCu.JLyZ3ErMJt8kEIl6SY6pjIGUZZq6cuS	ADMIN	admin
\.


--
-- Data for Name: vehicle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicle (id, department, model, plate_number, status, employee_id) FROM stdin;
2	Finance	Dizayer	AA-12378	Active	\N
4	IT	Corola	AA-65445	ACTIVE	\N
6	Transport	Abay	AA-12545	ACTIVE	\N
7	Audit	Toyota	AA-669985	ACTIVE	\N
8	Garage	Hilux	AA-99999	Active	\N
9	IT	TBYD	AA-951234	Active	\N
10	Transport	Toyota Hilux	AA-357951	Active	\N
3	Training	Mazda	AA-12345	ACTIVE	\N
13	Finance	Bajaje	AA-12378	Active	\N
14	Finance	Dizayer	AA-17378	Active	\N
16	Finance	Dizayer	AA-12378	Active	\N
17	Finance	Dizayer		Active	\N
19	Finance	Dizayer	AA-12378	Active	\N
20	Finance	Lada	AA-18878	Active	\N
18	Finance	Lada_Toyota	AA-18878	Active	\N
1	Finance	Lada_Toyota	AA-55555	Active	\N
21	Finance	xxx	AA-77378	Active	\N
23	Garage	Bajaj	AA-92299	Active	\N
\.


--
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_id_seq', 37, true);


--
-- Name: fuel_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fuel_stock_id_seq', 10, true);


--
-- Name: fuel_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fuel_transaction_id_seq', 25, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 280, true);


--
-- Name: vehicle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehicle_id_seq', 23, true);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: fuel_stock fuel_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fuel_stock
    ADD CONSTRAINT fuel_stock_pkey PRIMARY KEY (id);


--
-- Name: fuel_transaction fuel_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fuel_transaction
    ADD CONSTRAINT fuel_transaction_pkey PRIMARY KEY (id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vehicle vehicle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT vehicle_pkey PRIMARY KEY (id);


--
-- Name: fuel_transaction fk9kblblft9gmaq7e1c5gqs3ln1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fuel_transaction
    ADD CONSTRAINT fk9kblblft9gmaq7e1c5gqs3ln1 FOREIGN KEY (vehicle_id) REFERENCES public.vehicle(id);


--
-- Name: vehicle fkfjavg2xilewl4i6llmnwbde3t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicle
    ADD CONSTRAINT fkfjavg2xilewl4i6llmnwbde3t FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- PostgreSQL database dump complete
--

\unrestrict IVb4fRNlnSQVzzWeRTU5m3S7NY21Hi0jKL2HzyfJ0WkctKq1RCALWdg0vOj9LMc

